# Generated by Django 3.2.6 on 2021-10-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_shorten',
            name='orgin_url',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='url_shorten',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
